##controllers:
##    resource:
##        path: ../src/Controller/
##        namespace: App\Controller
##    type: attribute
controllers:
    resource: ../src/Infrastructure/Controller/
    type: attribute
