services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Domain/Entity/'
            - '../src/Application/DTO/'

    # Controladores
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    # Bind interface â†’ implementation
    App\Domain\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Doctrine\UserRepository
