services:
    # Carga autom√°tica de todos los servicios de src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Domain/Entity/'
            - '../src/Domain/Repository/'
            - '../src/Application/DTO/'

    # Controladores fuera de src/Controller
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags: ['controller.service_arguments']
